server:
    port: 8083

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://zipkin:9411
    cloud:
       gateway:
          routes:
            - id: candidate-service
                uri: lb://candidate-service
                predicates:
                  - Path=/candidates/**
                  - id: candidature-service
                    uri: lb://candidature-service
                    predicates:
                      - Path=/candidatures/**
                  - id: auth-service
                    uri: lb://auth-service
                    predicates:
                      - Path=/v1/**
                  - id: evaluation-service
                    uri: lb://evaluation-service
                    predicates:
                      - Path=/evaluation/**
                  - id: node-service
                    uri: lb://node-service
                    predicates:
                      - Path=/api/**
                  - id: employee-service
                    uri: lb://employee-service
                    predicates:
                      - Path=/employees/**
                  - id: offre-service
                    uri: lb://offre-service
                    predicates:
                      - Path=/offres/**

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true