server:
  port: 8086

  spring:
    application:
      name: offre-service
    h2:
      console:
        enabled: true
        path: /h2

    datasource:
      url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      username: sa
      password:
      driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto: create

  eureka:
      client:
          service-url:
              defaultZone: http://localhost:8761/eureka
          fetch-registry: true
          register-with-eureka: true